/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SetupProfileIndexRouteImport } from './routes/setup-profile/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as OrderCompleteIndexRouteImport } from './routes/order-complete/index'
import { Route as MyOrdersIndexRouteImport } from './routes/my-orders/index'
import { Route as MyAddressesIndexRouteImport } from './routes/my-addresses/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as DeliveryIndexRouteImport } from './routes/delivery/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as CartIndexRouteImport } from './routes/cart/index'
import { Route as CallbackIndexRouteImport } from './routes/callback/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupProfileIndexRoute = SetupProfileIndexRouteImport.update({
  id: '/setup-profile/',
  path: '/setup-profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderCompleteIndexRoute = OrderCompleteIndexRouteImport.update({
  id: '/order-complete/',
  path: '/order-complete/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyOrdersIndexRoute = MyOrdersIndexRouteImport.update({
  id: '/my-orders/',
  path: '/my-orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAddressesIndexRoute = MyAddressesIndexRouteImport.update({
  id: '/my-addresses/',
  path: '/my-addresses/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryIndexRoute = DeliveryIndexRouteImport.update({
  id: '/delivery/',
  path: '/delivery/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartIndexRoute = CartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackIndexRoute = CallbackIndexRouteImport.update({
  id: '/callback/',
  path: '/callback/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/products/$productId': typeof ProductsProductIdRoute
  '/callback': typeof CallbackIndexRoute
  '/cart': typeof CartIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/delivery': typeof DeliveryIndexRoute
  '/login': typeof LoginIndexRoute
  '/my-addresses': typeof MyAddressesIndexRoute
  '/my-orders': typeof MyOrdersIndexRoute
  '/order-complete': typeof OrderCompleteIndexRoute
  '/products': typeof ProductsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/setup-profile': typeof SetupProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/callback': typeof CallbackIndexRoute
  '/cart': typeof CartIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/delivery': typeof DeliveryIndexRoute
  '/login': typeof LoginIndexRoute
  '/my-addresses': typeof MyAddressesIndexRoute
  '/my-orders': typeof MyOrdersIndexRoute
  '/order-complete': typeof OrderCompleteIndexRoute
  '/products': typeof ProductsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/setup-profile': typeof SetupProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/products/$productId': typeof ProductsProductIdRoute
  '/callback/': typeof CallbackIndexRoute
  '/cart/': typeof CartIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/delivery/': typeof DeliveryIndexRoute
  '/login/': typeof LoginIndexRoute
  '/my-addresses/': typeof MyAddressesIndexRoute
  '/my-orders/': typeof MyOrdersIndexRoute
  '/order-complete/': typeof OrderCompleteIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/setup-profile/': typeof SetupProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/products/$productId'
    | '/callback'
    | '/cart'
    | '/checkout'
    | '/delivery'
    | '/login'
    | '/my-addresses'
    | '/my-orders'
    | '/order-complete'
    | '/products'
    | '/settings/'
    | '/setup-profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/products/$productId'
    | '/callback'
    | '/cart'
    | '/checkout'
    | '/delivery'
    | '/login'
    | '/my-addresses'
    | '/my-orders'
    | '/order-complete'
    | '/products'
    | '/settings'
    | '/setup-profile'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/products/$productId'
    | '/callback/'
    | '/cart/'
    | '/checkout/'
    | '/delivery/'
    | '/login/'
    | '/my-addresses/'
    | '/my-orders/'
    | '/order-complete/'
    | '/products/'
    | '/settings/'
    | '/setup-profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  CallbackIndexRoute: typeof CallbackIndexRoute
  CartIndexRoute: typeof CartIndexRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  DeliveryIndexRoute: typeof DeliveryIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  MyAddressesIndexRoute: typeof MyAddressesIndexRoute
  MyOrdersIndexRoute: typeof MyOrdersIndexRoute
  OrderCompleteIndexRoute: typeof OrderCompleteIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  SetupProfileIndexRoute: typeof SetupProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-profile/': {
      id: '/setup-profile/'
      path: '/setup-profile'
      fullPath: '/setup-profile'
      preLoaderRoute: typeof SetupProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-complete/': {
      id: '/order-complete/'
      path: '/order-complete'
      fullPath: '/order-complete'
      preLoaderRoute: typeof OrderCompleteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-orders/': {
      id: '/my-orders/'
      path: '/my-orders'
      fullPath: '/my-orders'
      preLoaderRoute: typeof MyOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-addresses/': {
      id: '/my-addresses/'
      path: '/my-addresses'
      fullPath: '/my-addresses'
      preLoaderRoute: typeof MyAddressesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery/': {
      id: '/delivery/'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/': {
      id: '/cart/'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback/': {
      id: '/callback/'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRouteWithChildren,
  ProductsProductIdRoute: ProductsProductIdRoute,
  CallbackIndexRoute: CallbackIndexRoute,
  CartIndexRoute: CartIndexRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  DeliveryIndexRoute: DeliveryIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  MyAddressesIndexRoute: MyAddressesIndexRoute,
  MyOrdersIndexRoute: MyOrdersIndexRoute,
  OrderCompleteIndexRoute: OrderCompleteIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  SetupProfileIndexRoute: SetupProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
