name: 'Setup Rust Environment'
description: 'Setup Rust toolchain with caching for Tauri builds'
inputs:
  rust-version:
    description: 'Rust version'
    required: false
    default: 'stable'
  targets:
    description: 'Rust targets to install (comma-separated)'
    required: false
    default: ''
  components:
    description: 'Rust components to install (comma-separated)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ inputs.rust-version }}
        targets: ${{ inputs.targets }}
        components: ${{ inputs.components }}

    - name: Setup sccache
      uses: mozilla-actions/sccache-action@v0.0.9

    - name: Configure sccache
      shell: bash
      run: |
        echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
        # Fallback settings in case GitHub Actions Cache is unavailable
        echo "SCCACHE_IDLE_TIMEOUT=0" >> $GITHUB_ENV

    - name: Setup Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: "frontend/apps/mizpos-desktop/src-tauri -> target"
        key: ${{ runner.os }}-rust-${{ inputs.rust-version }}
        shared-key: "rust-cache"
        save-if: ${{ github.ref == 'refs/heads/main' }}
        cache-on-failure: true