/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as StockRouteImport } from './routes/stock'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PublishersRouteImport } from './routes/publishers'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PosEmployeesRouteImport } from './routes/pos-employees'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CouponsRouteImport } from './routes/coupons'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AndroidEnterpriseRouteImport } from './routes/android-enterprise'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishersRoute = PublishersRouteImport.update({
  id: '/publishers',
  path: '/publishers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PosEmployeesRoute = PosEmployeesRouteImport.update({
  id: '/pos-employees',
  path: '/pos-employees',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsRoute = CouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AndroidEnterpriseRoute = AndroidEnterpriseRouteImport.update({
  id: '/android-enterprise',
  path: '/android-enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/android-enterprise': typeof AndroidEnterpriseRoute
  '/callback': typeof CallbackRoute
  '/change-password': typeof ChangePasswordRoute
  '/coupons': typeof CouponsRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/pos-employees': typeof PosEmployeesRoute
  '/products': typeof ProductsRoute
  '/publishers': typeof PublishersRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/android-enterprise': typeof AndroidEnterpriseRoute
  '/callback': typeof CallbackRoute
  '/change-password': typeof ChangePasswordRoute
  '/coupons': typeof CouponsRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/pos-employees': typeof PosEmployeesRoute
  '/products': typeof ProductsRoute
  '/publishers': typeof PublishersRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/android-enterprise': typeof AndroidEnterpriseRoute
  '/callback': typeof CallbackRoute
  '/change-password': typeof ChangePasswordRoute
  '/coupons': typeof CouponsRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/pos-employees': typeof PosEmployeesRoute
  '/products': typeof ProductsRoute
  '/publishers': typeof PublishersRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/android-enterprise'
    | '/callback'
    | '/change-password'
    | '/coupons'
    | '/events'
    | '/login'
    | '/logout'
    | '/pos-employees'
    | '/products'
    | '/publishers'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/stock'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/android-enterprise'
    | '/callback'
    | '/change-password'
    | '/coupons'
    | '/events'
    | '/login'
    | '/logout'
    | '/pos-employees'
    | '/products'
    | '/publishers'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/stock'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/android-enterprise'
    | '/callback'
    | '/change-password'
    | '/coupons'
    | '/events'
    | '/login'
    | '/logout'
    | '/pos-employees'
    | '/products'
    | '/publishers'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/stock'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AndroidEnterpriseRoute: typeof AndroidEnterpriseRoute
  CallbackRoute: typeof CallbackRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  CouponsRoute: typeof CouponsRoute
  EventsRoute: typeof EventsRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  PosEmployeesRoute: typeof PosEmployeesRoute
  ProductsRoute: typeof ProductsRoute
  PublishersRoute: typeof PublishersRoute
  ReportsRoute: typeof ReportsRoute
  SalesRoute: typeof SalesRoute
  SettingsRoute: typeof SettingsRoute
  StockRoute: typeof StockRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publishers': {
      id: '/publishers'
      path: '/publishers'
      fullPath: '/publishers'
      preLoaderRoute: typeof PublishersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos-employees': {
      id: '/pos-employees'
      path: '/pos-employees'
      fullPath: '/pos-employees'
      preLoaderRoute: typeof PosEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons': {
      id: '/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof CouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/android-enterprise': {
      id: '/android-enterprise'
      path: '/android-enterprise'
      fullPath: '/android-enterprise'
      preLoaderRoute: typeof AndroidEnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AndroidEnterpriseRoute: AndroidEnterpriseRoute,
  CallbackRoute: CallbackRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  CouponsRoute: CouponsRoute,
  EventsRoute: EventsRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  PosEmployeesRoute: PosEmployeesRoute,
  ProductsRoute: ProductsRoute,
  PublishersRoute: PublishersRoute,
  ReportsRoute: ReportsRoute,
  SalesRoute: SalesRoute,
  SettingsRoute: SettingsRoute,
  StockRoute: StockRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
