name: 'Deploy Lambda Function'
description: 'Deploy Lambda functions using Lambroll'
inputs:
  function-path:
    description: 'Path to Lambda function'
    required: true
  environment:
    description: 'Environment (dev/prod)'
    required: true
  aws-account-id:
    description: 'AWS Account ID'
    required: true
  lambroll-version:
    description: 'Lambroll version'
    required: false
    default: '1.3.2'

runs:
  using: 'composite'
  steps:
    - name: Install Lambroll
      shell: bash
      run: |
        if ! command -v lambroll &> /dev/null; then
          curl -L https://github.com/fujiwara/lambroll/releases/download/v${{ inputs.lambroll-version }}/lambroll_v${{ inputs.lambroll-version }}_linux_amd64.tar.gz | tar -xz
          sudo mv lambroll /usr/local/bin/
        fi

    - name: Deploy Lambda Function
      shell: bash
      working-directory: ${{ inputs.function-path }}
      run: |
        export ENV=${{ inputs.environment }}
        export AWS_ACCOUNT_ID=${{ inputs.aws-account-id }}
        make deploy