name: "Deploy Lambda Functions"
description: "Deploy Lambda Functions"

inputs:
  function-path:
    description: "Lambda Function Path"
    required: true
  environment:
    description: "Environment (dev, prod)"
    required: true
  aws-account-id:
    description: "AWS Account ID"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check uv exists
      id: check-uv
      shell: bash
      run: |
        if ! command -v uv &> /dev/null && [ ! -f "$HOME/.local/bin/uv" ]; then
          echo "uv is not installed"
          echo "exists=false" >> $GITHUB_OUTPUT
          exit 0
        fi
        echo "uv is installed"
        echo "exists=true" >> $GITHUB_OUTPUT

    - name: Install uv
      if: steps.check-uv.outputs.exists == 'false'
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Create requirements.txt
      shell: bash
      working-directory: ${{ inputs.function-path }}
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        uv pip compile pyproject.toml > requirements.txt

    - name: Deploy Lambda Functions
      shell: bash
      env:
        ENV: ${{ inputs.environment }}
        AWS_ACCOUNT_ID: ${{ inputs.aws-account-id }}
      working-directory: ${{ inputs.function-path }}
      run: |
        echo "Installing dependencies for ${{ inputs.function-path }} Lambda function..."
        pip install -r requirements.txt -t .
        echo "Deploying ${{ inputs.function-path }} Lambda function..."
        lambroll deploy \
          --function function.jsonnet \
          --ext-str ENV=${{ inputs.environment }} \
          --ext-str AWS_ACCOUNT_ID=${{ inputs.aws-account-id }} \
          --src . \
          --exclude-file .lambdaignore
