name: "Deploy Lambda Functions"
description: "Deploy Lambda Functions"

inputs:
  WORKING_DIR:
    description: "ディレクトリ"
    required: true
  ENV:
    description: "Env"
    required: true
  AWS_ACCOUNT_ID:
    description: "AWS Account ID"
    required: true
  LAMBDA_FUNTION_PATH:
    description: "Lambda Function Path"
    required: true

runs:
  using: "composite"
  steps:
    - name: install uv
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Create requirements.txt
      shell: bash
      working-directory: ${{ inputs.LAMBDA_FUNTION_PATH }}
      run: |
        uv pip compile pyproject.toml > requirements.txt

    - name: Deploy Lambda Functions
      shell: bash
      env:
        ENV: ${{ inputs.ENV }}
        AWS_ACCOUNT_ID: ${{ inputs.AWS_ACCOUNT_ID }}
      working-directory: ${{ inputs.LAMBDA_FUNTION_PATH }}
      run: |
        echo "Installing dependencies for ${{ inputs.LAMBDA_FUNTION_PATH }} Lambda function..."
        pip install -r requirements.txt -t .
        echo "Deploying ${{ inputs.LAMBDA_FUNTION_PATH }} Lambda function..."
        lambroll deploy \
          --function function.jsonnet \
          --ext-str ENV=${{ inputs.ENV }} \
          --ext-str AWS_ACCOUNT_ID=${{ inputs.AWS_ACCOUNT_ID }} \
          --src . \
          --exclude-file .lambdaignore
