/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SelectEventRouteImport } from './routes/select-event'
import { Route as RegisterTerminalRouteImport } from './routes/register-terminal'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PosRouteImport } from './routes/pos'
import { Route as OpeningRouteImport } from './routes/opening'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExchangeRouteImport } from './routes/exchange'
import { Route as ClosingRouteImport } from './routes/closing'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectEventRoute = SelectEventRouteImport.update({
  id: '/select-event',
  path: '/select-event',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterTerminalRoute = RegisterTerminalRouteImport.update({
  id: '/register-terminal',
  path: '/register-terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const OpeningRoute = OpeningRouteImport.update({
  id: '/opening',
  path: '/opening',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeRoute = ExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const ClosingRoute = ClosingRouteImport.update({
  id: '/closing',
  path: '/closing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/closing': typeof ClosingRoute
  '/exchange': typeof ExchangeRoute
  '/login': typeof LoginRoute
  '/opening': typeof OpeningRoute
  '/pos': typeof PosRoute
  '/refund': typeof RefundRoute
  '/register-terminal': typeof RegisterTerminalRoute
  '/select-event': typeof SelectEventRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/closing': typeof ClosingRoute
  '/exchange': typeof ExchangeRoute
  '/login': typeof LoginRoute
  '/opening': typeof OpeningRoute
  '/pos': typeof PosRoute
  '/refund': typeof RefundRoute
  '/register-terminal': typeof RegisterTerminalRoute
  '/select-event': typeof SelectEventRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/closing': typeof ClosingRoute
  '/exchange': typeof ExchangeRoute
  '/login': typeof LoginRoute
  '/opening': typeof OpeningRoute
  '/pos': typeof PosRoute
  '/refund': typeof RefundRoute
  '/register-terminal': typeof RegisterTerminalRoute
  '/select-event': typeof SelectEventRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/closing'
    | '/exchange'
    | '/login'
    | '/opening'
    | '/pos'
    | '/refund'
    | '/register-terminal'
    | '/select-event'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/closing'
    | '/exchange'
    | '/login'
    | '/opening'
    | '/pos'
    | '/refund'
    | '/register-terminal'
    | '/select-event'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/closing'
    | '/exchange'
    | '/login'
    | '/opening'
    | '/pos'
    | '/refund'
    | '/register-terminal'
    | '/select-event'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClosingRoute: typeof ClosingRoute
  ExchangeRoute: typeof ExchangeRoute
  LoginRoute: typeof LoginRoute
  OpeningRoute: typeof OpeningRoute
  PosRoute: typeof PosRoute
  RefundRoute: typeof RefundRoute
  RegisterTerminalRoute: typeof RegisterTerminalRoute
  SelectEventRoute: typeof SelectEventRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-event': {
      id: '/select-event'
      path: '/select-event'
      fullPath: '/select-event'
      preLoaderRoute: typeof SelectEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-terminal': {
      id: '/register-terminal'
      path: '/register-terminal'
      fullPath: '/register-terminal'
      preLoaderRoute: typeof RegisterTerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opening': {
      id: '/opening'
      path: '/opening'
      fullPath: '/opening'
      preLoaderRoute: typeof OpeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange': {
      id: '/exchange'
      path: '/exchange'
      fullPath: '/exchange'
      preLoaderRoute: typeof ExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/closing': {
      id: '/closing'
      path: '/closing'
      fullPath: '/closing'
      preLoaderRoute: typeof ClosingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClosingRoute: ClosingRoute,
  ExchangeRoute: ExchangeRoute,
  LoginRoute: LoginRoute,
  OpeningRoute: OpeningRoute,
  PosRoute: PosRoute,
  RefundRoute: RefundRoute,
  RegisterTerminalRoute: RegisterTerminalRoute,
  SelectEventRoute: SelectEventRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
